### ISSUE TITLE
Add to Cart from Wish List marks all as added

### ISSUE THREAD

**Issue by bholbrook73** [Focus-College/ecommerce-website#28]
Description
----------
Clicking Add to Cart from wishlist shows all items in wishlist as added

Steps to Reproduce
---------
1. Add multiple items to wishlist
2. Go to wishlist
3. Click "Add to cart"
4. Witness All items show added to cart

Expected Behaviour
----------
Only items clicked "Added to Cart" should show "Added to Cart"

**Comment by dwaffle** [comment]
Fixed by passing item.product into the IsInCart() as well as changing the button handler.  This fix may may have also fixed #27
